### ISSUE TITLE
Use Thaumcraft ideas for a video game

### ISSUE THREAD

**Issue by Mystic-Ervo** [Azanor/thaumcraft-suggestions#147]
Hi Azanor

I'm developing a video game in which its history is developed in a society in which science is based on what I like to call "magic technology", a science in which magic and technology come together to create innovative inventions. I would like to separate the magic into several branches, but I have run out of ideas for the different sorts of magicians.
I love Thaumcraft, it's my favorite magic mod and it's inspired me a lot for the project I'm creating, so it occurred to me that I could separate the magicians into three classes: thaumaturges, golemancers, and alchemists; but before doing it I want to ask you permission to use them, since the idea is yours and I would not like to use it if you don't want to.
All I need to use are basic tools of each class (such as the thaumometer, wands, revelation glasses, traveler's boots, golemancer's bell, etc.) and the name of the classes.
Obviously you will have your recognition in the credits of the video game, and if you need more information of the video game, do not hesitate to ask me.

Thank you very much for your time ^^

**Comment by Azanor** [comment]
I hate to do this, but I am going to have to say no. While I can't claim IP on basic ideas like alchemists and so forth, very specific things like the thaumometer and so forth is definite parts of the Thaumcraft IP and I have definite plans to make use of that IP for things other than just a mod.

**Comment by Mystic-Ervo** [comment]
Oh… But within those ideas that I can use are included the classes of thaumaturges and golemancers?
The tools like thaumometer, revelation glasses, traveler's boots, etc… aren't decisive in the development of video game and I can replace them with other things, but the classes…

**Comment by Azanor** [comment]
The classes you listed are generic and not something I have claim on.

**Comment by Mystic-Ervo** [comment]
Great!! ^^
Thank you for answering me 😆
