### ISSUE TITLE
Nerf Imbued Fire

### ISSUE THREAD

**Issue by pdewilde** [Azanor/thaumcraft-suggestions#152]
imbued fire really destroys servers. Its spread should be limited to something like 64 or 128 blocks from origin to prevent destroying entire world on multiplayer server

**Comment by Azanor** [comment]
Whatever imbued fire is, it is not part of thaumcraft.

**Comment by Shahelion** [comment]
I know this is late, but more information is always good, right?

Imbued Fire is from Thaumic Tinkerer, and I'm pretty sure it's intended to be world-destroying, as it would be too powerful if it were limited in range.
