### ISSUE TITLE
The server crashes then i try put arcane bore

### ISSUE THREAD

**Issue by ghost** [Azanor/thaumcraft-suggestions#183]
The server crashes then i try put arcane bore
[crash-2018-02-11_00.04.31-server.txt](https://github.com/Azanor/thaumcraft-suggestions/files/1713766/crash-2018-02-11_00.04.31-server.txt)

**Comment by MCShammer** [comment]
This is the place for suggestions not bug reports. Please look to the thaumcraft 6 project, this issue has been reported already.
