### ISSUE TITLE
Please cap essentia jars at a multiple of 10 instead of 256

### ISSUE THREAD

**Issue by McFrugal** [Azanor/thaumcraft-suggestions#212]
Essentia phials carry 10.  TC4 allowed you to completely empty a jar by applying phials to it, but with a cap of 256 that's not possible.

**Comment by webwraith** [comment]
That's true, perhaps having phials carry either 8 or 16 essentia instead would be useful?

**Comment by Alcamore** [comment]
I'm a fan of the change to 10 essentia per phial, makes getting the right number of phials for a specific recipe easier to figure out, especially with many recipes using multiples of 5 or 10 essentia. I think capping it at 250 essentia per jar makes sense.

**Comment by Azanor** [comment]
Not a bad suggestion tbh.
