### ISSUE TITLE
Feature Request: Convenient Plate Crafting

### ISSUE THREAD

**Issue by Azanor** [Azanor/thaumcraft-suggestions#216]
_From @weds4 on March 23, 2018 21:37_

Could the recipes for Brass, Iron, Thaumium and Void Metal Plates be modified so that they can be crafted using plates and ingots i.e. you need two more plates and have one, so you craft 1 plate and 2 ingots to yield 3 plates? This would not break balance, and could reduce some early game hassle (before Alchemical Automation) and limit waste of more expensive materials like void metal.

_Copied from original issue: Azanor/thaumcraft-beta#417_

**Comment by l-Luna** [comment]
But that kinda removes the whole point.

**Comment by Azanor** [comment]
Yup, I don't see the point of this either.

**Comment by weds4** [comment]
I guess the point would be to have a way to make plates one at a time, so you only have to make as many as are needed for a particular recipe. Unless the point of plates is to make it so there are unused materials cluttering up your chests?
