### ISSUE TITLE
harness GUI visible by other players :bug

### ISSUE THREAD

**Issue by superon** [Azanor/thaumcraft-suggestions#25]
just that really, another player has reported to me that they're seeing the harness "pop up" on their screen when i'm charging it, even though they don't even own a harness:/
 the TC version is the latest one 5.2.4 and using forge-1.8.9-11.15.1.1847 with this list of mods:
![screen shot 2016-04-13 at 00 38 04](https://cloud.githubusercontent.com/assets/5957924/14581715/60ba00ae-03eb-11e6-81c2-7ce379a94c4e.png)
let me know if any other info will be useful or indeed if the provided information wasn't.

**Comment by Hyxaru** [comment]
I'd recommend closing this issue on this github, and opening an exact copy of this one at the _proper_ github.
https://github.com/Azanor/thaumcraft-5/issues

**Comment by superon** [comment]
thanks, good to know for future things.
though i just went there and seen someone else already posted this issue 5 days ago so seems there's no point:)
