### ISSUE TITLE
Abandoned Crates, Old Urns, Loot Bags drops

### ISSUE THREAD

**Issue by Antillar** [Azanor/thaumcraft-suggestions#29]
It appears that Abandoned Crate has some items dropped from it with a chance less than 1 in 10 000 000. What was the reason for making this and can this possibly get fixed? I do not believe that someone will ever break that many of Abandoned Crates to obtain the items.

Thaumcraft version 4.2.3.5

**Comment by Hyxaru** [comment]
What items if I may ask?

**Comment by Antillar** [comment]
Most detailed information here: http://ftbwiki.org/Abandoned_Crate (just finished today)
Look for Void metal Ingot stuff (armor + sword).

**Comment by Azanor** [comment]
Don't believe everything you read in a Wiki. I say this because I don't actually add any if the void items and such to the drop tables. If they are present there they must have been added in a modpack or something.

**Comment by Antillar** [comment]
Well, I am the one who currently writes Thaumcraft and its addons. So, if there are no void items in the drop tables, I will change the article. But what items are in the drop table and what is their chance? 
Unfortunately I couldn't find the drop table itself, so I used a script designed by our head admin to simulate breaking of the block and to count the drops.
