### ISSUE TITLE
Translation to pt_br

### ISSUE THREAD

**Issue by CallBatman** [Azanor/thaumcraft-suggestions#299]
Just want to know if I can translate to pt_br with no problems. Basically asking for permission.

**Comment by Geethebluesky** [comment]
The language files are left here specifically for that. If no one's done it already I'm pretty confident in saying go ahead :)

**Comment by Velken** [comment]
I am already over 50% on that. If you want, we can compare the translations.

**Comment by CallBatman** [comment]
I didn't start it yet, was just being sure that I could do it. But we can compare later, if you will.

**Comment by CallBatman** [comment]
@Velken so, I done 50% of the translation. Would you like to compare them?
