### ISSUE TITLE
About Multiplayer

### ISSUE THREAD

**Issue by Leor3x** [Azanor/thaumcraft-suggestions#322]
So I have been waiting for Thaumcraft 6 for a while and got really excited today when I saw it was avaliable. I told a friend to play, created a server with Hamachi and began playing. Everything was doing fine until the moment we began doing stuff with the Thaumonomicon. So, each time one of us would do a discovery, it wouldn't unlock anything for the other. That's understandable for singleplayer or for a massive server in which each player would play on their own, but it's not something very enjoyable for us. Is there a way to make us both unlock things at the same time? Thanks for reading, and hope to get an answer soon.

**Comment by Morinor** [comment]
Research isnt supposed to work that way, that doesnt really make sense.
Every player is supposed to research on their own, having others can help with resources tho.
(If Thaumic Tinkerer gets to TC6, i might add the research sharing again)
