### ISSUE TITLE
[Suggestion] Bring wands back

### ISSUE THREAD

**Issue by BobbyKilkins** [Azanor/thaumcraft-suggestions#354]
I love the new Thaumcraft 6 overhaul of the aura, the vis crystals in the arcane workbench, the new focci manipulation system. There is only one thing I don't like: the Caster's Gauntlet. Why a gauntlet anyways? How about bringing back wands, just to replace the gauntlet? After all, (except for crafting and creating constructs) wands were used almost exactly like the gauntlet right now. What kind of magic mod is complete without magic wands? This will also not require lots of work, just using the old wand textures and maybe changing some text in the Thaumonomicon.

**Comment by webwraith** [comment]
Because it's a magic based tech mod. As in, magic seen through the eye of an alchemist, rather than a wizard. Azanor decided to _replace_ the wands with the gauntlet, so I doubt they're going to reverse that decision.

**Comment by Snowydeath** [comment]
I love the reasoning behind removing wands, it's a really awesome idea! I never even thought about that being the reason wands were removed.

**Comment by BobbyKilkins** [comment]
When you say it like that, the gauntlet actually seems a better idea.
