### ISSUE TITLE
Research Table Automation

### ISSUE THREAD

**Issue by zt64** [Azanor/thaumcraft-suggestions#364]
One thing I would really like to see in Thaumcraft 6 is the ability to automate the research table.  Like have paper be able to be automatically inserted and scribing tools inserted and took out whenever they loose their durability.  Basically what im asking is add inputs and outputs for certain sides on the research table or  maybe even a new block for automation.  Anyways,  I would love to see this added to Thaumcraft 6.

**Comment by praecipitator** [comment]
That would be nice. You do research, and a golem keeps fetching you paper and ink.

Also, when I read the title of your suggestion, I thought you want to automate the process of researching. I thought: "That doesn't even make sense!", but then I remembered: we have brains in jars. Outsource research to several zombie brains, build a literal Think Tank! What could possibly go wrong?!

What could go wrong, besides you gaining a lot of warp, though? It could attract (=spawn) angry zombies, mind spiders, stuff like that. Or there is a risk that the think tank explodes, releasing a floating brain abomination, which attacks you with taint bolts!
