### ISSUE TITLE
Iron Capped Wooden Wand missing

### ISSUE THREAD

**Issue by AngelGamerZ** [Azanor/thaumcraft-suggestions#470]
In the last Beta (Beta26) The Starting Item "Iron Capped Wooden Wand" is missing. Also the recipe itself is missing

**Comment by Morinor** [comment]
Its not supposed to be there

**Comment by dmarcuse** [comment]
Wands aren't a thing in Thaumcraft 6. To get started, collect some vis crystals and you'll get clues to continue from there.

**Comment by AngelGamerZ** [comment]
Ah okay so im the stupid one here :_D

Thanks :)
