### ISSUE TITLE
Adding a way to "fix" Clogged Flux Condenser Lattice

### ISSUE THREAD

**Issue by Thepawer** [Azanor/thaumcraft-suggestions#477]
Could be expensive or not, or maybe adding an use could also be nice. Although I understand that the purpose of them turning into clogged is to make them useless after that.

**Comment by wamc2017** [comment]
There's already a way to fix the clogged lattices, right click them with an essentia filter.

**Comment by Thepawer** [comment]
Thanks, I never realized lol.
