### ISSUE TITLE
Duplication Glitch Thaumcraft-1.7.10-4.2.3.5

### ISSUE THREAD

**Issue by Gohu29** [Azanor/thaumcraft-suggestions#82]
https://www.youtube.com/watch?v=sx7uiBlBpx4

Dupe with an Hungry Chest, warp itemduct and resonant retriever (from thermal dynamics).

Only work with Hungry chest.

**Comment by majijn** [comment]
this is the repository for suggestions, 
the one for bugs is https://github.com/Azanor/thaumcraft-5/issues
